spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3
    password: 123456
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        max-wait: 3
student:
  name:
    张三
teacher:
  name:
    李四